image-cache: Ignore SIGPIPE
During restore, the function send_image_async() is writing to a socket.
However, this might fail with EPIPE (Broken pipe), causing the image-cache
process to receive SIGPIPE.

The default behaviour for this signal is to terminate the process, causing
the restore to fail with:

    Restore side is calling finish
    Error (criu/img-remote.c:287): Unable to connect to local socket: img-cache.sock: Connection refused
    Error (criu/img-remote.c:1093): Error opening local connection for RESTORE_FINISH:null
    Error (criu/img-remote.c:1154): Unable to open finish restore connection
    Error (criu/cr-restore.c:2661): Finish remote restore failed.

This patch is ignores SIGPIPE and allows the send_image_async() to
handle EPIPE.

Signed-off-by: Radostin Stoyanov <rstoyanov1@gmail.com>