ppc64/restore.h: fix for clang
Apparently, clang 3.8 ppc doesn't know the register name 'sp'.

> criu/cr-restore.c:3179:2: error: unknown register name 'sp' in asm
>         JUMP_TO_RESTORER_BLOB(new_sp, restore_task_exec_start,
> task_args);
>         ^
> /criu/criu/arch/ppc64/include/asm/restore.h:24:5: note: expanded from
> macro 'JUMP_TO_RESTORER_BLOB'
>                 : "sp", "1", "2", "3", "12", "memory")
>                   ^
> 1 error generated.

According to docs, stack pointer is r1.

Cc: Laurent Dufour <ldufour@linux.vnet.ibm.com>
Signed-off-by: Kir Kolyshkin <kir@openvz.org>