restore: Don't finish_remote_restore on detached
When --restore-detached is used with image-{cache, proxy} the
following errors were shown after successful restore.

Error (criu/img-remote.c:775): Error opening local connection for RESTORE_FINISH:null                                                                                   │
Error (criu/img-remote.c:836): Unable to open finish restore connection
Error (criu/cr-restore.c:2615): Finish remote restore failed.

Signed-off-by: Radostin Stoyanov <rstoyanov1@gmail.com>